development:
  adapter: postgresql
  encoding: unicode
  database: events_backend_development
  pool: 5
  username: inmobi
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: events_backend_test
  pool: 5
  username: inmobi
  password: