development:
  adapter: postgresql
  encoding: unicode
  database: events_development
  pool: 5
  username: mistiko 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: events_test
  pool: 5
  username: mistiko
  password:
